### ISSUE TITLE
White screen after docker compose installation

### ISSUE THREAD

**Issue by Huddeij** [danielbrendel/hortusfox-web#125]
I get after succesful installation via docker compose a white screen. Neither browser network inspection delivers anything, nor the log output of the hortusfox container. I assume, the external database is connected successfully, because I don't get the ~ `waiting for database connection` error anymore. The only thing I get is the page title shown by the tab in the browser which says: `Asatru PHP - Exception`. I tried it via reverse proxxy and directly from the ip addres, neither worked.

Device and System:
- Asus R556L
- Fedora 39
- Docker 25.0.3

docker-compose.yml
```
version: "3.8"

services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    container_name: hortusfox
    ports:
      - "8355:80"
    volumes:
      - /mnt/ntfs/docker/hortusfox/images:/var/www/html/public/img
      - ./logs:/var/www/html/app/logs
      - /mnt/ntfs/docker/hortusfox/backup:/var/www/html/public/backup
    environment:
      APP_ADMIN_EMAIL: "admin@xxxxxxx.de"
      APP_ADMIN_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxx"
      APP_BASE_DIR: ""
      APP_DEBUG: "true"
      APP_LANG: "de"
      APP_WORKSPACE: "Sabikos Indoor Jungle"
      APP_ENABLE_SCROLLER: "true"
      APP_OVERLAY_ALPHA: "null"
      APP_ENABLE_CHAT: "false"
      APP_ONLINE_MINUTE_LIMIT: 15
      APP_SHOW_CHAT_ONLINE_USERS: "false"
      APP_SHOW_CHAT_TYPING_INDICATOR: "false"
      APP_OVERDUE_TASK_HOURS: 10
      APP_CRON_PW: "test"
      APP_CRON_MAIL_LIMIT: 2
      APP_ENABLE_HISTORY: "true"
      APP_HISTORY_NAME: "Historie"
      APP_ENABLE_PHOTO_SHARE: "false"
      PHOTO_RESIZE_FACTOR_DEFAULT: 1.0
      PHOTO_RESIZE_FACTOR_1: 0.5
      PHOTO_RESIZE_FACTOR_2: 0.4
      PHOTO_RESIZE_FACTOR_3: 0.4
      PHOTO_RESIZE_FACTOR_4: 0.3
      PHOTO_RESIZE_FACTOR_5: 0.2
      DB_HOST: mysql
      DB_PORT: 6603
      DB_DATABASE: hortus
      DB_USERNAME: hortus
      DB_PASSWORD: xxxxxxxxxxxxxxx
      DB_CHARSET: "utf8mb4"
      SMTP_FROMNAME: xxxxxxxx.de
      SMTP_FROMADDRESS: admin@xxxxxxx.de
      SMTP_HOST: "mail.smtp2go.com"
      SMTP_PORT: 587
      SMTP_USERNAME: "xxxxxx.de"
      SMTP_PASSWORD: "xxxxxxxxxxxxxxx"
      SMTP_ENCRYPTION: tls
      LOG_ENABLE: "true"
    networks:
      - mysql
      - hortus
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  mysql:
    name: mysql_default
    external: true
  hortus:
    name: hortus
```

logs:
```
192.168.0.45 - - [24/Feb/2024:12:26:35 +0000] "GET / HTTP/1.1" 200 974 "-" "Mozilla/5.0 (Windows NT 10.0; rv:121.0) Gecko/20100101 Firefox/121.0"

192.168.0.45 - - [24/Feb/2024:12:26:35 +0000] "GET /favicon.ico HTTP/1.1" 200 973 "http://192.168.0.28:8355/" "Mozilla/5.0 (Windows NT 10.0; rv:121.0) Gecko/20100101 Firefox/121.0"

192.168.0.45 - - [24/Feb/2024:12:27:44 +0000] "GET / HTTP/1.1" 200 974 "-" "Mozilla/5.0 (Windows NT 10.0; rv:121.0) Gecko/20100101 Firefox/121.0"

172.26.0.1 - - [24/Feb/2024:12:30:17 +0000] "GET / HTTP/1.1" 200 1229 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/99.0.4844.47 Mobile/15E148 Safari/604.1"

172.26.0.1 - - [24/Feb/2024:12:30:18 +0000] "GET /favicon.ico HTTP/1.1" 200 918 "https://plant.xxxxxxxx.de/" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/99.0.4844.47 Mobile/15E148 Safari/604.1"

172.26.0.1 - - [24/Feb/2024:12:30:18 +0000] "GET / HTTP/1.1" 200 1229 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/99.0.4844.47 Mobile/15E148 Safari/604.1"

172.26.0.1 - - [24/Feb/2024:12:30:18 +0000] "GET /favicon.ico HTTP/1.1" 200 918 "https://plant.xxxxxxx.de/" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/99.0.4844.47 Mobile/15E148 Safari/604.1"
```

caddyfile:
```
# Hortusfox
plant.{$DOMAIN} {
	reverse_proxy 192.168.0.28:8355
	encode zstd gzip
	header {
		Strict-Transport-Security max-age=31536000; includeSubDomains; preload
		X-Xss-Protection 1; mode=block
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy strict-origin-when-cross-origin
		Content-Security-Policy upgrade-insecure-requests
		Cache-Control public, max-age=15, must-revalidate
		Feature-Policy "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'self'; camera 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none';       magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'none'; usb 'none'; vr 'none'"
	}
}
```
