### ISSUE TITLE
Authentication issues with Mariadb 11

### ISSUE THREAD

**Issue by adrianbn** [danielbrendel/hortusfox-web#193]
**Describe the bug**
I was having issues getting the docker compose to work due to authentication errors. The web service would never become available because it would fail to auth to the mariadb container. The mariadb container would show the following error:
```
Version: '11.3.2-MariaDB-1:11.3.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-05-07  3:50:38 3 [Warning] Access denied for user 'hortusfox'@'192.168.192.3' (using password: YES)
2024-05-07  3:50:43 4 [Warning] Access denied for user 'hortusfox'@'192.168.192.3' (using password: YES)
```

I found this comment in another issue https://github.com/danielbrendel/hortusfox-web/issues/101#issuecomment-1927290177 and decided to change the mariadb version from latest (currently 11) to 10 and that solved the issue. 

**To Reproduce**
This is the dockerfile I am using, just a slight modification from the one on the repo. This works as long as the mariadb image is pointed to version 10 (as in the example), and fails to authenticate if you change it to latest.
```
services:
  app:
    container_name: hortusfox-web
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    ports:
      - "${HORTUSFOX_HTTP_PORT}:80" 
    volumes:
      - app_images:/var/www/html/public/img
      - app_logs:/var/www/html/app/logs
      - app_backup:/var/www/html/public/backup
      - app_themes:/var/www/html/public/themes
      - app_migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: "${HORTUSFOX_ADMIN_EMAIL}"
      APP_ADMIN_PASSWORD: "${HORTUSFOX_ADMIN_PASSWORD}"
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: hortusfox
      DB_USERNAME: "${HORTUSFOX_DB_USERNAME}"
      DB_PASSWORD: "${HORTUSFOX_DB_PASSWORD}"
      DB_CHARSET: "utf8mb4"
    depends_on:
      - db
    networks:
      - hortusfox-net

  db:
    container_name: hortusfox-db
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${HORTUSFOX_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: hortusfox
      MYSQL_USER: "${HORTUSFOX_DB_USERNAME}"
      MYSQL_PASSWORD: "${HORTUSFOX_DB_PASSWORD}"
    networks:
      - hortusfox-net
    volumes:
      - db_data:/var/lib/mysql

networks:
  hortusfox-net:

volumes:
  db_data:
  app_images:
  app_logs:
  app_backup:
  app_themes:
  app_migrate:
```

1. Change the `image: mariadb:10` line for `image: mariadb`.
2. Start the compose stack w/ docker compose up...
3. check the DB / App logs with docker logs <container-name>

**Expected behavior**
It should authenticate correctly with version 11 as well. 

**Screenshots**

**Software:**
- HortusFox version
- PHP Version
- MySQL version (if related to the problem)
- Docker version if used in a docker environment
- Changes to your docker-compose file if altered

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Smartphone (please complete the following information):**

**Additional context**
