### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by kenske** [danielbrendel/hortusfox-web#270]
**Describe the bug**
The app is reporting the wrong time. This seems to be causing issues with the activity log.

![image](https://github.com/user-attachments/assets/cb3cdfbf-b8bc-4979-b62b-27771f4aacf2)

**To Reproduce**
1. Go to the Admin area
2. Click on `Info`
3. Scroll down to `Server`
4. Reported time is incorrect

**Screenshots**
![image](https://github.com/user-attachments/assets/a7ce38b5-09a4-4c0b-a1a7-795fc4d09f78)

**Expected behavior**
The time in the screenshot should be `03:29`

If I start a shell in the hortusfox docker container and check the date:

```
root@2992820401a1:/var/www/html# date
Wed Sep 11 22:28:59 CDT 2024
root@2992820401a1:/var/www/html# date -u
Thu Sep 12 03:28:55 UTC 2024
```

**Software:**
- HortusFox version - 3.4
- PHP Version - 8.3.0
- Docker version if used in a docker environment - 25.0.3
- Changes to your docker-compose file if altered

Here are the environment variables I'm using:

```
    environment:
      APP_ADMIN_EMAIL: "redacted"
      APP_ADMIN_PASSWORD:
      DB_HOST: redacted
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: hortusfox
      DB_PASSWORD:
      DB_CHARSET: "utf8mb4"
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 130.0
