### ISSUE TITLE
Error when changing settings under environment tab

### ISSUE THREAD

**Issue by wgalternate** [danielbrendel/hortusfox-web#315]
**Describe the bug**

Error when changing any settings in the environment admin area.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tasks_enable' in 'SET'

**To Reproduce**
1. Go to Environment tab in admin area
2. Click on Save
3. See error

**Expected behavior**
Settings able to be tweaked?

**Screenshots**

**Software:**
PHP Version: 8.3.0
MySQL Version: 11.6.2-MariaDB-ubu2404
Docker Desktop on Macos
Server: Linux #1 SMP Thu Oct 24 19:28:55 UTC 2024 on aarch64

**Docker Compose**
```
version: "3.8"

services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    container_name: hortusfox
    ports:
      - "8585:80"
    volumes:
      - app_images:/var/www/html/public/img
      - app_logs:/var/www/html/app/logs
      - app_backup:/var/www/html/public/backup
      - app_themes:/var/www/html/public/themes
      - app_migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: -
      APP_ADMIN_PASSWORD: -
      APP_TIMEZONE: "UTC"
      DB_HOST: hortusfox-db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: -
      DB_PASSWORD: -
      DB_CHARSET: "utf8mb4"
    depends_on:
      - db
    networks:
      macserver_bridge:
        ipv4_address: 172.5.0.8 

  db:
    image: mariadb
    container_name: hortusfox-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: -
      MYSQL_DATABASE: hortusfox
      MYSQL_USER: -
      MYSQL_PASSWORD: -
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      macserver_bridge:
        ipv4_address: 172.5.0.9

volumes:
  db_data:
  app_images:
  app_logs:
  app_backup:
  app_themes:
  app_migrate:


networks:
  macserver_bridge:
    external: true
```
