### ISSUE TITLE
Unable to create/export backup after upgrading from v3.5 to v4.2

### ISSUE THREAD

**Issue by Appoxo** [danielbrendel/hortusfox-web#350]
**Describe the bug**
Unable to create backup after upgrading from v3.5 to v4.2 (via docker)

**To Reproduce**
1. Go to /admin?tab=backup (navigating the web-ui to the backup tab)
2. Click on "Export"

**Expected behavior**
Download of a zip-archive

**Screenshots**

**Software:**
- HortusFox v4.2
- PHP Version: 8.3.0
- MySQL Version: 11.4.5-MariaDB-ubu2404
- Server: `Linux #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1~bpo11+1 (2024-05-06) auf x86_64`
- Docker engine version: 28.0.0

compose:
**old**
```yaml
  hortusFox:
    image: ghcr.io/danielbrendel/hortusfox-web:v3.5
    container_name: hortusFox
    depends_on:
      - traefik
      - mariadb
    expose:
      - 80
    networks:
      - service
    volumes:
      - ${DIR_LOCALTIME}:/etc/localtime
      - ${DIR_container}/hortusfox/app_images:/var/www/html/public/img
      - ${DIR_container}/hortusfox/app_logs:/var/www/html/app/logs
      - ${DIR_container}/hortusfox/app_backup:/var/www/html/public/backup
      - ${DIR_container}/hortusfox/app_themes:/var/www/html/public/themes
      - ${DIR_container}/hortusfox/app_migrate:/var/www/html/app/migrations
    env_file:
      - hortus-fox.env
    labels:
      # Traefik:
      traefik.enable: true
      # Traefik rules for hortusFox:
      traefik.http.services.hortusFox.loadbalancer.server.port: 80
      traefik.http.routers.hortusFox-public.entrypoints: 'https'
      traefik.http.routers.hortusFox-public.rule: 'Host(`hortusfox.${DOMAIN_EXTERNAL}`)'
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    expose:
      - 3306
    networks:
      - service
    volumes:
      - ${DIR_container}/mariadb/db_data:/var/lib/mysql
    env_file:
      - hortus-fox.env
    restart: always
```
**new**
```yaml
  hortusFox:
    image: ghcr.io/danielbrendel/hortusfox-web:v4.2
    container_name: hortusFox
    depends_on:
      - traefik
      - mariadb
    expose:
      - 80
    networks:
      - service
    volumes:
      - ${DIR_LOCALTIME}:/etc/localtime
      - ${DIR_container}/hortusfox/app_images:/var/www/html/public/img
      - ${DIR_container}/hortusfox/app_logs:/var/www/html/app/logs
      - ${DIR_container}/hortusfox/app_backup:/var/www/html/public/backup
      - ${DIR_container}/hortusfox/app_themes:/var/www/html/public/themes
      - ${DIR_container}/hortusfox/app_migrate:/var/www/html/app/migrations
    env_file:
      - hortus-fox.env
    labels:
      # Traefik:
      traefik.enable: true
      # Traefik rules for hortusFox:
      traefik.http.services.hortusFox.loadbalancer.server.port: 80
      traefik.http.routers.hortusFox-public.entrypoints: 'https'
      traefik.http.routers.hortusFox-public.rule: 'Host(`hortusfox.${DOMAIN_EXTERNAL}`)'
    restart: unless-stopped
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    expose:
      - 3306
    networks:
      - service
    volumes:
      - ${DIR_container}/mariadb/db_data:/var/lib/mysql
    env_file:
      - hortus-fox.env
    restart: always
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 135.0 x64

**Additional context**
When trying to configure the automatic backup it errors out with a red banner message

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'auto_backup' in 'SET' "

Config used:
```
Cronjob URL: https://hortusfox.EXTERNAL.TLD/cronjob/backup/auto
Optional backup location: /var/www/html/public/backup
```
