### ISSUE TITLE
Internal Server Error 500 When Clear Last fertilised Date

### ISSUE THREAD

**Issue by ounyai** [danielbrendel/hortusfox-web#359]
**Describe the bug**
The bug occurs when you edit the date of the Last fertilised field, then select the calendar icon, select the clear option and save. This causes a server 500\error, 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any plant.
2. Edit pre-defined Last fertilised field
3. Select calendar icon
4. Select 'Clear' option
5. Save

**Expected behaviour**
Expected date to save and return user to plant page.

**Screenshots**
Added.  [Screenshot

![Image](https://github.com/user-attachments/assets/f6152b84-eb97-4776-9b55-b631a6050e9a)

](https://eserv.au/assets/misc/error.png)

**Software:**
- Running in Docker with provided standard docker-compose.yml template.
- HortusFox version: latest
- PHP Version
- MySQL version (if related to the problem): MariaDB 8.0.41-1.el9
- Docker version if used in a docker environment: Docker version 27.4.1, build b9d17ea
- Changes to your docker-compose file if altered

```
version: "3.8"

services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    ports:
      - "8080:80"
    volumes:
      - app_images:/var/www/html/public/img
      - app_logs:/var/www/html/app/logs
      - app_backup:/var/www/html/public/backup
      - app_themes:/var/www/html/public/themes
      - app_migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: "xxxxxx"
      APP_ADMIN_PASSWORD: "xxxxxxxx"
      APP_TIMEZONE: "Australia/Sydney"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: xxxx
      DB_PASSWORD: xxxxxxxx
      DB_CHARSET: "utf8mb4"
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxx
      MYSQL_DATABASE: hortusfox
      MYSQL_USER: xxxxxx
      MYSQL_PASSWORD: xxxxxxxx
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_images:
  app_logs:
  app_backup:
  app_themes:
  app_migrate:
```
