### ISSUE TITLE
Adding Cover Photo doesn't work

### ISSUE THREAD

**Issue by JCPvanHooren** [danielbrendel/hortusfox-web#394]
**Describe the bug**
I'm new to HortusFox, so if I'm doing it wrong, please let me know, but clicking the upload icon for the main/cover photo of any new plant doesn't work.

**To Reproduce**
1. Go to any stored plant
2. Click on the 'up' arrow in the main/cover photo phrame

**Expected behavior**
I'd expect to get an upload dialog, similar to adding a photo in the Photos section.

**Software:**
- Installation: Docker 
- HortusFox Version: 4.6
- PHP Version: 8.3.0
- MySQL version: MariaDB 11.5.2 (I'd like to use my pre-existing MariaDB instead of a separate instance for HortusFox)
- Docker version: 24.0.2
- Changes to your docker-compose file if altered:

```
services:
  HortusFox:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    container_name: HortusFox
    ports:
      - 8080:80
    volumes:
      - /volume1/docker/HortusFox/images:/var/www/html/public/img
      - /volume1/docker/HortusFox/logs:/var/www/html/app/logs
      - /volume1/docker/HortusFox/backup:/var/www/html/public/backup
      - /volume1/docker/HortusFox/themes:/var/www/html/public/themes
      - /volume1/docker/HortusFox/migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: "joostvanhooren@gmail.com"
      APP_ADMIN_PASSWORD: "admin_pwd"
      APP_TIMEZONE: "CET"
      DB_HOST: myMariaDB
      DB_PORT: 3306
      DB_DATABASE: HortusFox
      DB_USERNAME: HF
      DB_PASSWORD: "db_pwd"
      DB_CHARSET: "utf8mb4"
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox/Chrome
 - Version 137.0.2 / 134.0.6998.205

**Additional context:**
If I manually reference a photo.jpg file in the DB, uploaded through the Photos section, the cover image works fine.
